version: 2
jobs:
  build_sqlite:
    docker:
      - image: greenbone/build-env-gvm-master-debian-stretch-gcc-sqlite
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone --depth 1 https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd
      - checkout
      - run:
          name: Configure and Compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
  build_postgresql:
    docker:
      - image: greenbone/build-env-gvm-master-debian-stretch-gcc-postgresql
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone --depth 1 https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd
      - checkout
      - run:
          name: Configure and Compile
          command: mkdir build && cd build/ && cmake -DBACKEND=POSTGRESQL -DCMAKE_BUILD_TYPE=Release .. && make install
  doc_coverage:
    docker:
      - image: greenbone/code-metrics-doxy-coverage-debian-stretch
    steps:
      - checkout
      - run:
          name: Generate documentation (XML)
          command: mkdir build && cd build/ && cmake -DSKIP_SRC=1 .. && make doc-xml 2> ~/doxygen-stderr.txt
      - run:
          name: Establish coverage
          command: ~/doxy-coverage/doxy-coverage.py ~/project/build/doc/generated/xml/ > ~/documentation-coverage.txt
      - store_artifacts:
          path: ~/doxygen-stderr.txt
      - store_artifacts:
          path: ~/documentation-coverage.txt
workflows:
  version: 2
  build:
    jobs:
      - build_sqlite
      - build_postgresql
      - doc_coverage

